# Generated by Django 5.2.1 on 2025-05-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_correo_usuario_email_remove_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nombre',
        ),
    ]
